// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: api/protos/subscription.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description            string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BestValue              bool                   `protobuf:"varint,3,opt,name=bestValue,proto3" json:"bestValue,omitempty"`
	UsdPrice               int64                  `protobuf:"varint,4,opt,name=usdPrice,proto3" json:"usdPrice,omitempty"`
	Price                  map[string]int64       `protobuf:"bytes,5,rep,name=price,proto3" json:"price,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ExpectedMonthlyPrice   map[string]int64       `protobuf:"bytes,6,rep,name=expectedMonthlyPrice,proto3" json:"expectedMonthlyPrice,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalCostBilledOneTime string                 `protobuf:"bytes,7,opt,name=totalCostBilledOneTime,proto3" json:"totalCostBilledOneTime,omitempty"`
	OneMonthCost           string                 `protobuf:"bytes,8,opt,name=oneMonthCost,proto3" json:"oneMonthCost,omitempty"`
	TotalCost              string                 `protobuf:"bytes,9,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	FormattedBonus         string                 `protobuf:"bytes,10,opt,name=formattedBonus,proto3" json:"formattedBonus,omitempty"`
	RenewalText            string                 `protobuf:"bytes,11,opt,name=renewalText,proto3" json:"renewalText,omitempty"`
	RenewalBonusExpected   map[string]int64       `protobuf:"bytes,13,rep,name=renewalBonusExpected,proto3" json:"renewalBonusExpected,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_api_protos_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_api_protos_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetBestValue() bool {
	if x != nil {
		return x.BestValue
	}
	return false
}

func (x *Plan) GetUsdPrice() int64 {
	if x != nil {
		return x.UsdPrice
	}
	return 0
}

func (x *Plan) GetPrice() map[string]int64 {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Plan) GetExpectedMonthlyPrice() map[string]int64 {
	if x != nil {
		return x.ExpectedMonthlyPrice
	}
	return nil
}

func (x *Plan) GetTotalCostBilledOneTime() string {
	if x != nil {
		return x.TotalCostBilledOneTime
	}
	return ""
}

func (x *Plan) GetOneMonthCost() string {
	if x != nil {
		return x.OneMonthCost
	}
	return ""
}

func (x *Plan) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

func (x *Plan) GetFormattedBonus() string {
	if x != nil {
		return x.FormattedBonus
	}
	return ""
}

func (x *Plan) GetRenewalText() string {
	if x != nil {
		return x.RenewalText
	}
	return ""
}

func (x *Plan) GetRenewalBonusExpected() map[string]int64 {
	if x != nil {
		return x.RenewalBonusExpected
	}
	return nil
}

type PaymentProviders struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icons                []string               `protobuf:"bytes,3,rep,name=icons,proto3" json:"icons,omitempty"`
	Data                 map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SupportsSubscription bool                   `protobuf:"varint,2,opt,name=supportsSubscription,proto3" json:"supportsSubscription,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentProviders) Reset() {
	*x = PaymentProviders{}
	mi := &file_api_protos_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentProviders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentProviders) ProtoMessage() {}

func (x *PaymentProviders) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentProviders.ProtoReflect.Descriptor instead.
func (*PaymentProviders) Descriptor() ([]byte, []int) {
	return file_api_protos_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentProviders) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentProviders) GetIcons() []string {
	if x != nil {
		return x.Icons
	}
	return nil
}

func (x *PaymentProviders) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PaymentProviders) GetSupportsSubscription() bool {
	if x != nil {
		return x.SupportsSubscription
	}
	return false
}

type PaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Provider      *PaymentProviders      `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_api_protos_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_api_protos_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentMethod) GetProvider() *PaymentProviders {
	if x != nil {
		return x.Provider
	}
	return nil
}

var File_api_protos_subscription_proto protoreflect.FileDescriptor

const file_api_protos_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/protos/subscription.proto\"\xd4\x05\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tbestValue\x18\x03 \x01(\bR\tbestValue\x12\x1a\n" +
	"\busdPrice\x18\x04 \x01(\x03R\busdPrice\x12&\n" +
	"\x05price\x18\x05 \x03(\v2\x10.Plan.PriceEntryR\x05price\x12S\n" +
	"\x14expectedMonthlyPrice\x18\x06 \x03(\v2\x1f.Plan.ExpectedMonthlyPriceEntryR\x14expectedMonthlyPrice\x126\n" +
	"\x16totalCostBilledOneTime\x18\a \x01(\tR\x16totalCostBilledOneTime\x12\"\n" +
	"\foneMonthCost\x18\b \x01(\tR\foneMonthCost\x12\x1c\n" +
	"\ttotalCost\x18\t \x01(\tR\ttotalCost\x12&\n" +
	"\x0eformattedBonus\x18\n" +
	" \x01(\tR\x0eformattedBonus\x12 \n" +
	"\vrenewalText\x18\v \x01(\tR\vrenewalText\x12S\n" +
	"\x14renewalBonusExpected\x18\r \x03(\v2\x1f.Plan.RenewalBonusExpectedEntryR\x14renewalBonusExpected\x1a8\n" +
	"\n" +
	"PriceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aG\n" +
	"\x19ExpectedMonthlyPriceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aG\n" +
	"\x19RenewalBonusExpectedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xda\x01\n" +
	"\x10PaymentProviders\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05icons\x18\x03 \x03(\tR\x05icons\x12/\n" +
	"\x04data\x18\x04 \x03(\v2\x1b.PaymentProviders.DataEntryR\x04data\x122\n" +
	"\x14supportsSubscription\x18\x02 \x01(\bR\x14supportsSubscription\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\rPaymentMethod\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12-\n" +
	"\bprovider\x18\x02 \x01(\v2\x11.PaymentProvidersR\bproviderB\tZ\a/protosb\x06proto3"

var (
	file_api_protos_subscription_proto_rawDescOnce sync.Once
	file_api_protos_subscription_proto_rawDescData []byte
)

func file_api_protos_subscription_proto_rawDescGZIP() []byte {
	file_api_protos_subscription_proto_rawDescOnce.Do(func() {
		file_api_protos_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_subscription_proto_rawDesc), len(file_api_protos_subscription_proto_rawDesc)))
	})
	return file_api_protos_subscription_proto_rawDescData
}

var file_api_protos_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_protos_subscription_proto_goTypes = []any{
	(*Plan)(nil),             // 0: Plan
	(*PaymentProviders)(nil), // 1: PaymentProviders
	(*PaymentMethod)(nil),    // 2: PaymentMethod
	nil,                      // 3: Plan.PriceEntry
	nil,                      // 4: Plan.ExpectedMonthlyPriceEntry
	nil,                      // 5: Plan.RenewalBonusExpectedEntry
	nil,                      // 6: PaymentProviders.DataEntry
}
var file_api_protos_subscription_proto_depIdxs = []int32{
	3, // 0: Plan.price:type_name -> Plan.PriceEntry
	4, // 1: Plan.expectedMonthlyPrice:type_name -> Plan.ExpectedMonthlyPriceEntry
	5, // 2: Plan.renewalBonusExpected:type_name -> Plan.RenewalBonusExpectedEntry
	6, // 3: PaymentProviders.data:type_name -> PaymentProviders.DataEntry
	1, // 4: PaymentMethod.provider:type_name -> PaymentProviders
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_protos_subscription_proto_init() }
func file_api_protos_subscription_proto_init() {
	if File_api_protos_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_subscription_proto_rawDesc), len(file_api_protos_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protos_subscription_proto_goTypes,
		DependencyIndexes: file_api_protos_subscription_proto_depIdxs,
		MessageInfos:      file_api_protos_subscription_proto_msgTypes,
	}.Build()
	File_api_protos_subscription_proto = out.File
	file_api_protos_subscription_proto_goTypes = nil
	file_api_protos_subscription_proto_depIdxs = nil
}
