// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/protos/vpn.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lantern_StreamLogs_FullMethodName = "/Lantern/StreamLogs"
)

// LanternClient is the client API for Lantern service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanternClient interface {
	StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
}

type lanternClient struct {
	cc grpc.ClientConnInterface
}

func NewLanternClient(cc grpc.ClientConnInterface) LanternClient {
	return &lanternClient{cc}
}

func (c *lanternClient) StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Lantern_ServiceDesc.Streams[0], Lantern_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Lantern_StreamLogsClient = grpc.ServerStreamingClient[LogLine]

// LanternServer is the server API for Lantern service.
// All implementations must embed UnimplementedLanternServer
// for forward compatibility.
type LanternServer interface {
	StreamLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogLine]) error
	mustEmbedUnimplementedLanternServer()
}

// UnimplementedLanternServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanternServer struct{}

func (UnimplementedLanternServer) StreamLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogLine]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLanternServer) mustEmbedUnimplementedLanternServer() {}
func (UnimplementedLanternServer) testEmbeddedByValue()                 {}

// UnsafeLanternServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanternServer will
// result in compilation errors.
type UnsafeLanternServer interface {
	mustEmbedUnimplementedLanternServer()
}

func RegisterLanternServer(s grpc.ServiceRegistrar, srv LanternServer) {
	// If the following call pancis, it indicates UnimplementedLanternServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lantern_ServiceDesc, srv)
}

func _Lantern_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LanternServer).StreamLogs(m, &grpc.GenericServerStream[emptypb.Empty, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Lantern_StreamLogsServer = grpc.ServerStreamingServer[LogLine]

// Lantern_ServiceDesc is the grpc.ServiceDesc for Lantern service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lantern_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Lantern",
	HandlerType: (*LanternServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Lantern_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/protos/vpn.proto",
}
