// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/protos/vpn.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanternService_StreamLogs_FullMethodName = "/LanternService/StreamLogs"
)

// LanternServiceClient is the client API for LanternService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanternServiceClient interface {
	StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
}

type lanternServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanternServiceClient(cc grpc.ClientConnInterface) LanternServiceClient {
	return &lanternServiceClient{cc}
}

func (c *lanternServiceClient) StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LanternService_ServiceDesc.Streams[0], LanternService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LanternService_StreamLogsClient = grpc.ServerStreamingClient[LogLine]

// LanternServiceServer is the server API for LanternService service.
// All implementations must embed UnimplementedLanternServiceServer
// for forward compatibility.
type LanternServiceServer interface {
	StreamLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogLine]) error
	mustEmbedUnimplementedLanternServiceServer()
}

// UnimplementedLanternServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanternServiceServer struct{}

func (UnimplementedLanternServiceServer) StreamLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogLine]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLanternServiceServer) mustEmbedUnimplementedLanternServiceServer() {}
func (UnimplementedLanternServiceServer) testEmbeddedByValue()                        {}

// UnsafeLanternServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanternServiceServer will
// result in compilation errors.
type UnsafeLanternServiceServer interface {
	mustEmbedUnimplementedLanternServiceServer()
}

func RegisterLanternServiceServer(s grpc.ServiceRegistrar, srv LanternServiceServer) {
	// If the following call pancis, it indicates UnimplementedLanternServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanternService_ServiceDesc, srv)
}

func _LanternService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LanternServiceServer).StreamLogs(m, &grpc.GenericServerStream[emptypb.Empty, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LanternService_StreamLogsServer = grpc.ServerStreamingServer[LogLine]

// LanternService_ServiceDesc is the grpc.ServiceDesc for LanternService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanternService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LanternService",
	HandlerType: (*LanternServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LanternService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/protos/vpn.proto",
}
