tags := "lanternd,with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api,with_tailscale,with_conntrack"
lanternd := if os() == "windows" { "lanternd.exe" } else { "lanternd" }
lantern := if os() == "windows" { "lantern.exe" } else { "lantern" }

build-daemon:
    go build -tags "{{tags}}" -o ../bin/{{lanternd}} ./lanternd

run-daemon *args:
    go run -tags={{tags}} ./lanternd run {{args}}

build-cli:
    go build -o ../bin/{{lantern}} ./lantern
