base_tags := "with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api,with_tailscale,with_conntrack"
tags := if os() == "macos" { "standalone," + base_tags } else { base_tags }
lanternd := if os() == "windows" { "lanternd.exe" } else { "lanternd" }
lantern := if os() == "windows" { "lantern.exe" } else { "lantern" }

build-daemon:
    go build -tags "{{tags}}" -o ../bin/{{lanternd}} ./lanternd

run-daemon *args:
    go run -tags={{tags}} ./lanternd run {{args}}

cli_tags := if os() == "macos" { "standalone" } else { "" }

build-cli:
    go build {{ if cli_tags != "" { "-tags " + cli_tags } else { "" } }} -o ../bin/{{lantern}} ./lantern
