# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Check for slog overwrite calls in tests
      run: |
        if grep -rn 'slog\.SetDefault\|slog\.SetLogLoggerLevel' --include='*_test.go' .; then
          echo "::error::Test files should not upate the slog.Default logger or level. This pollutes the output."
          exit 1
        fi

    - name: Build
      run: go build -v -tags with_clash_api ./...
    - name: Test
      run: go test -v -tags with_clash_api ./...
